# Generated by Django 3.1.7 on 2021-06-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='dateandtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
